---
kind: pipeline
type: docker
name: CI
steps:
  - name: cargo check
    image: rust
    commands:
      - cargo check

  - name: cargo test
    image: rust
    commands:
      - cargo test

  - name: cargo format
    image: rust
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  - name: cargo clippy
    image: rust
    commands:
      - cargo clippy -- -D warnings

---
kind: signature
hmac: 5679be2f0894641063c405b0f70f1cceba5332c40b13ef0c43852a97b06eaf92

...
