---
kind: pipeline
type: docker
name: CI
steps:
  - name: cargo check
    image: rust
    commands:
      - cargo check

  - name: cargo test
    image: rust
    commands:
      - cargo test

  - name: cargo format
    image: rust
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  - name: cargo clippy
    image: rust
    commands:
      - rustup component add clippy
      - cargo clippy -- -D warnings

---
kind: signature
hmac: 3af9f2acdbf7653904324aaffe4dc6cbef09e5478b15247c700fdd04b9711d0f

...
