[package]
name = "dfm"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1

[dependencies]
async-recursion = "0.3"
clap = "2.33"
futures = "0.3"
git2 = "0.13"
tokio = { version = "1.10", features = ["fs", "macros", "rt-multi-thread"] }
xdg = "2.2"
